### ISSUE TITLE
useSourcemaps: true breaks logging after the first log

### ISSUE THREAD

**Issue by gcpantazis** [sprucelabsai/sprucebot-log#8]
With `useSourcemaps: true` I've noticed that I'll see one log post, then subsequent logs fail to post. I've tested this by triggering the same log in the same way (throwing an error at the load of a page), but haven't tested it by throwing logs in different ways.

`useSourcemaps: false` fixes this.

**Comment by kengoldfarb** [comment]
We now default to `useSourcemaps=false`
